### ISSUE TITLE
in '/api/songs' apis it need 'song_skins' tables in sqlite

### ISSUE THREAD

**Issue by tanhzongbei** [bui/taiko-web#107]
﻿###### 下記の問題を説明してください。 スクリーンショットと診断情報を含めてください。
###### Describe the problem you are having below. Please include a screenshot and the diagnostic information.
 in '/api/songs' it need 'song_skins' tables in sqlite,but in 'setup' it doesn't include

**Comment by fdioni** [comment]
```
[2019-01-15 07:36:19,793] ERROR in app: Exception on /api/songs [GET]
Traceback (most recent call last):
  File "/srv/taiko-web/.venv2/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/taiko-web/.venv2/local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/taiko-web/.venv2/local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/taiko-web/.venv2/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/taiko-web/.venv2/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/taiko-web/app.py", line 171, in route_api_songs
    raw_song_skins = query_db('select * from song_skins')
  File "/srv/taiko-web/app.py", line 25, in query_db
    cur = get_db().execute(query, args)
OperationalError: no such table: song_skins
```

this log from supervisor Taiko web

**Comment by fdioni** [comment]
it's my solution

if you already have running taiko-web, add 'song_skins' column using this sql command
`ALTER TABLE "songs" ADD COLUMN (`song_skins` INTEGER);`

and then add 'song_skins' table
`CREATE TABLE "song_skins" ( `id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, `name` TEXT NOT NULL, `song` INTEGER, `stage` TEXT NOT NULL, `don` TEXT NOT NULL);
`

**Comment by tanhzongbei** [comment]
in fact I saw this api from its website the 'song_skin ' all return None,so skip the db query and return None is ok

**Comment by bui** [comment]
I've updated the setup page. Sorry for the confusion.
